import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import SuggestedUsers from "@/components/SuggestedUsers";
import TrendingTopics from "@/components/TrendingTopics";
import Providers from "./providers";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Providers>
          {/* Fixed side gutters to avoid flicker when pages update */}
          <div className="hidden lg:block fixed inset-y-0 left-0 w-150 bg-black z-0 gutter-left" aria-hidden />
          <div className="hidden lg:block fixed inset-y-0 right-0 w-150 bg-black z-0 gutter-right" aria-hidden />

          {/* Thin vertical divider lines placed at the inner edge of the gutters (visible, fixed) */}
          <div className="hidden lg:block fixed inset-y-0 left-150 w-px bg-white/30 z-10 pointer-events-none divider-left" aria-hidden />
          <div className="hidden lg:block fixed inset-y-0 right-150 w-px bg-white/30 z-10 pointer-events-none divider-right" aria-hidden />

          <div className="relative z-20">
            <Header />
            <div className="mx-auto w-full max-w-6xl flex flex-row justify-center relative">
              <main className="w-full max-w-2xl mx-auto z-10">{children}</main>
              <aside className="hidden xl:flex flex-col gap-6 fixed right-8 top-24 w-[320px]">
                <SuggestedUsers />
                <TrendingTopics />
              </aside>
            </div>
          </div>
        </Providers>
      </body>
    </html>
  );
}
